services:

  db:
    image: postgres:18-alpine
    container_name: pg18
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "example"
    ports:
      - "5987:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: